version: "3.7"

##networks:
##  monitor-promografa:
##    driver: bridge
    
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
      
  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"      
      
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.2
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"  
      
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"   
      
  prometheus_ifood:
    container_name: prometheus-ifood
    image: prometheus-ifood
    ports:
      - "9090:9090"
    labels:
      org.label-schema.group: "monitoring"
      
  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:6.5.0
    ports:
      - "3000:3000"

  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.11.0
    environment: 
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin    
    ports:
      - "8161:8161"    
      - "1883:1883"
      - "5445:5445"
      - "5672:5672"
      - "9404:9404"
      - "61613:61613"   
      - "61616:61616"   
      
  mongodb_ifood:
    container_name: mongodb_ifood
    image: mongo:4.2.5-bionic
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: pedido
      MONGO_INITDB_ROOT_PASSWORD: pedido
      MONGO_INITDB_DATABASE: pedido      
      
  zookeeper:
    container_name: zookeeper_container
    image: debezium/zookeeper:1.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    container_name: kafka_container
    image: debezium/kafka:1.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.87:9092
     
     
  kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
       KAFKA_BROKERCONNECT: 192.168.1.87:9092
    ports:
     - 9000:9000
    depends_on:
      - kafka      
      