CREATE TABLE public.restaurant (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creationdate timestamp NULL,
	identification varchar(255) NULL,
	"name" varchar(255) NULL,
	"owner" varchar(255) NULL,
	updatedate timestamp NULL,
	localization_id int8 NULL,
	CONSTRAINT restaurant_pkey PRIMARY KEY (id)
);
ALTER TABLE public.restaurant ADD CONSTRAINT fk71sc79egh0hg4aoahtbt7ye0k FOREIGN KEY (localization_id) REFERENCES localization(id);




CREATE TABLE public.dish (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	price numeric(19,2) NULL,
	restaurant_id int8 NULL,
	CONSTRAINT dish_pkey PRIMARY KEY (id)
);
ALTER TABLE public.dish ADD CONSTRAINT fkt13glsbe9ivpka00hbeg539cv FOREIGN KEY (restaurant_id) REFERENCES restaurant(id);